### ISSUE TITLE
MyModel.get(Array<int>) does not consistently return an array

### ISSUE THREAD

**Issue by steren** [sebelga/gstore-node#134]
I migrated from gstore-node 1 to 4, and my app is now breaking due to a behavior change:

Before, when I was calling MyModel.get() with an array, I always got in return an array of entities.
Now, when I call MyModel.get() with an array of one int, I get an entity in return. However, if I call it with an array of 2 ints, I get an array in return.

The fact that the method does not consistently return an array when invoked with an array makes it hard to use, as my code always expects the same output.

**Comment by sebelga** [comment]
Good point @micaww about maintaining the Array type even if provided with 1 id. The thing is now it might break a lot of apps that might have migrated to the current behavior.

**Comment by steren** [comment]
Note that this regression happened between v1 and v4.

**Comment by sebelga** [comment]
Yes, that's the problem 😊 It is too old to just revert as a patch. It was intentional that if you pass an integer/string id, you receive the entity (not an Array with an entity in it). Receiving an array back from the `get()` with a single id seemed wrong to me.

A solution to not create a breaking change now would be to have another get() method that would maintain the Array if an one is provided (even with only 1 id). Then you'd have to do a search & replace on that new method. Would that work?

**Comment by steren** [comment]
That would work for me yes, it would prevent me from doing an extra check
to ensure the output is an array.
I would recommend something like `getArray`

**Comment by sebelga** [comment]
Ok I put it in the pipe. Quite busy right now (new job, new house, new country! 😄)  If you feel like doing a PR great, otherwise I'll do it asap.

**Comment by sebelga** [comment]
Hello,
Sorry for the _very_ late answer on this issue. I finally got a chance to get back to it. I decided that it made more sense to correct the behavior of the `.get()` method and bump a new major version of gstore with the fix. `v6.0.0` should now correctly return an array of entity when an array of ids is passed to the `Model.get()`.

Feel free to re-open this issue if the issue persist. Cheers! 👍
