### ISSUE TITLE
query on this package

### ISSUE THREAD

**Issue by o1lab** [sebelga/gstore-node#14]
Im playing around with GAE, datastore and came across this package. Taking this along lines of mongoose is really good.

One of the major complaints of GAE datastore seems to be you will be locked into google-eco-system and cant migrate to other database engines.

So what do you think about having a 'new or this' package which will act as an abstraction layer on top of datastore, mongoose and mysql. One package - talk to mongoose or datastore or mysql

This means an application 'migration'  is easy and more users.

I havent used mongoose or datastore intensively - so wanted to know what you feel about this proposal ?

**Comment by sebelga** [comment]
Hi,
It's true that by using Google Datastore you are kind of locked in, specially because of the way the architecture works with Entities relationship (ancestors), entity key namespace...
If an "abstraction layer" were to be made you could not have database normalization as you have with MySQL tables and foreign keys. So really all your business logic would be much different according to what database you target. Then if you would want to migrate from the Datastore to MySQL you would then need to rethink completely the way you store your data.
That being said you can export your entities from the datastore as CSV file to import them in other database.
