### ISSUE TITLE
MyModel.delete() doesn't work with string ids

### ISSUE THREAD

**Issue by theArina** [sebelga/gstore-node#207]

**Comment by sebelga** [comment]
Just to make sure, you are saying that it does not work with an `Array` of string ids, is that correct?

**Comment by theArina** [comment]
I'm pretty sure that it's both, single id and array

**Comment by sebelga** [comment]
Hello,
I finally got a chance to look at it. Indeed, `MyModel.get()` `MyModel.update()` and `MyModel.delete()` don't work with string **id**. You need to parse it to integer first

```js
const id = '1234';
MyModel.delete(+id);
```

This is because Datastore treats a string as `"name"` in the entity key and not `"id"`. I plan on updating the gstore API (next major version) for those methods where you would have to specify if you are providing a Key `id` or a Key `name`. Probably something like this:

```js
const id = '1234';
MyModel.delete({ id });
```

Cheers 👍

**Comment by sebelga** [comment]
I will close this issue as it will be solved with this issue: https://github.com/sebelga/gstore-node/issues/212
