### ISSUE TITLE
Validation failure on save only returns first error

### ISSUE THREAD

**Issue by pauloddr** [sebelga/gstore-node#72]
Hello,

while looking at the code to investigate why Gstore was returning only the first error as opposed to all of them (like ORMs normally do), I found this piece of code inside `validateEntityData()` in __model.js__:

```javascript
                if (!validate.success) {
                    delete validate.success;
                    return validate.errors[Object.keys(validate.errors)[0]];
                }
```

As a result, `Model.save()` on validation failure returns only the first error. 

Is there a reason for that? Couldn't we just return `validate.errors` in its entirety?

**Comment by sebelga** [comment]
Hello,
It has been implemented like this by design but you're right that it could output all the errors at once. As for now, until I can dedicate time to improve the error handling, you can validate the entity before saving (not as nice I know :) and you should have all the errors there.

```js
const user = new User({ name: 'John' });
const validate = user.validate();
// If you have any errors they will be inside validate.errors
```

It makes me see that I should return proper error codes for each type of validation error.
thanks

**Comment by pauloddr** [comment]
Thanks for the workaround. Also error codes would be awesome. Node core is heading that way as well (as seen [here](https://medium.com/the-node-js-collection/node-js-errors-changes-you-need-to-know-about-dc8c82417f65)).

**Comment by sebelga** [comment]
thanks for the link 👍  I will follow that pattern.

**Comment by sebelga** [comment]
Hi,
I just release v2.0.0 that should fix this issue and return all the errors with proper error codes.
Let me know if there is any more issue. thanks!
