### ISSUE TITLE
Select in a query fails when two properties are used

### ISSUE THREAD

**Issue by cristyansv** [sebelga/gstore-node#74]
By running the following code:
```javascript
      db
          .ProjectModel
          .query()
          .select(['name', 'updateOn']);
```
You get the following error

```
Error: no matching index found. recommended index is:<br/>- kind: Project<br/>  properties:<br/>  - name: name<br/>  - name: updateOn<br/>
    at /Users/cristyansepulveda/visualive_website/node_modules/grpc/src/node/src/client.js:569:15 code: 412, metadata: Metadata { _internal_repr: {} } }
```

model:

```javascript
const ProjectSchema = new Schema({
    name:     {type: 'string'},
    updateOn: {type: 'datetime', default: gstore.defaultValues.NOW},
  });
```

**Comment by cristyansv** [comment]
Investigating discovered that this error happens by not having a designated [composite index](Investigating discovered that this error happens by not having a designated composite index.).

**Comment by cristyansv** [comment]
Investigating discovered that this error happens by not having a designated [composite index](Investigating discovered that this error happens by not having a designated composite index.).

**Comment by micaww** [comment]
Hey @cristyansv!

The error that you are receiving is actually coming from the google-cloud/datastore module, and not gstore-node.

You are getting this error because if you send Datastore a query that involves the use of more than one index, you must create a [composite index](https://cloud.google.com/datastore/docs/tools/indexconfig) for those two properties. Since you are only asking Datastore for only two properties, it will only get its data from those 2 indexes (instead of retrieving the whole object and removing all other properties).
Fortunately, google-cloud-node even tells you how it thinks you should structure your index!

To add this composite index, create an `index.yaml` file by your `app.yaml` file with these contents:
```yaml
indexes:
  - kind: Project
    properties:
      - name: name
      - name: updateOn  
```

Then you can update the index by issuing this command from your shell in your project directory:

`gcloud datastore create-indexes index.yaml`

Where index.yaml is that file you just created.

It'll take a few minutes for the index to be created and all of your documents to be reindexed, but then you will be able to use that query no problemo!

**Comment by micaww** [comment]
You can also just take out the `.select()` part of your query and not have to define a composite index. This will also be a little bit slower because DS will return the entire item. You may not want this though, because maybe you have a lot of data.

Retrieving from the indexes alone will _always_ be significantly faster. Especially when paging through lots of data, like yours will.

**Comment by sebelga** [comment]
Thanks @micaww for the explanation. Yes indeed the error is because you need to generate the indexes for your query. You can do as micaww says or if you are using the Datastore Emulator it can generate the indexes for you.  
The command is:
`gcloud datastore create-indexes ~/path/to/your/local-datastore/WEB-INF/index.yaml`

I will close the issue as it is not related to gstore-node.
thanks
