### ISSUE TITLE
Not possible to get an entity with id "1"

### ISSUE THREAD

**Issue by vovayartsev** [sebelga/gstore-node#86]
Because of this function:

```
function parseId(id) {
    return isFinite(id) ? parseInt(id, 10) : id;
}
```

The call `User.get("1")` tries to find an entity with a numeric ID instead of a String ID.
This is great for a codebase written from scratch, but causes problems when dealing with legacy.

**Comment by sebelga** [comment]
Hello,
With the latest version (2.1.2) there is a new option for the schema to avoid the conversion of integer into strings: **keyType**  

```js
const schema = new gstore.Schema({
    ... // your properties
}, {
    keyType: 'name'
})
```

This should fix the problem, let me know if the problem persists

**Comment by ZackKnopp** [comment]
@sebelga 
I'm using gstore-node v5.0.1 and I'm having an issue updating an entity that uses a non-numeric id. The id is automatically parsed into a numeric one, which changes the value. I have set the keyType to "name" on my schema.

My datastore entity id/name is "200200000000000016353" and it gets turned into "200200000000000000000" because of rounding from parseInt and integer limits of js.

Why does gstore-node still use parseId, even when keyType is set on the schema? Is this expected?

Possible solutions?
- Don't use parseId when keyType="name"
- Check id with Number​.MAX_SAFE_INTEGER?


Here is my schema:
```
const classSchema = new Schema(
  {
    Name: { type: String, required: true },
    customer: { type: Schema.Types.Key, ref: "Customer", required: true }
  },
  { keyType: "name" }
);
```

In model.js of your library you have an update function:
```
static update(id, data, ancestors, namespace, transaction, options) {
        this.__hooksEnabled = true;
        const _this = this;

        let entityUpdated;
        let error = {};

        id = parseId(id);  <--- problem

        ...
}
```

What do you think?
